### ISSUE TITLE
[Improvement] Better to give proper name all packs residing directory

### ISSUE THREAD

**Issue by aparnawso2** [wso2/product-ei#124]
Better to give proper name all packs residing directory instead of wso2. I would suggest "Runtimes".

<EI_HOME>
     |_wso2
          |_analytics
          |_broker
          |_business-process
          |_components
          |_lib
          |_tmp

**Comment by himasha** [comment]
Content inside 'wso2' directory are not just runtimes but also includes components and libs which are shared by all runtimes. This structure is to represent the agreed structure in C5 where content inside 'wso2' folder should not be changed/configured by users. However there is a limitation in EI, with regards to conf folder of these runtimes ( where users might have to make changes) because we can't use deployment.yaml in this C4 context without a major refactoring.
