### ISSUE TITLE
Unable to Localize the Notifications Label in the Human Task Explorer

### ISSUE THREAD

**Issue by praneesha** [wso2/product-ei#1503]
[**Description:**]
![bulgarian-ui](https://user-images.githubusercontent.com/11707273/33817067-70a9083a-de63-11e7-8eca-e5c965eae7ae.png)
![bulgarian-ui incorrect](https://user-images.githubusercontent.com/11707273/33817068-70e253f6-de63-11e7-921d-2801af5321dc.png)

When localizing the Human Task Explorer as per [1], it was identified that changing the following strings in the <EI_HOME>/wso2/business-process/repository/deployment/server/jaggeryapps/humantask-explorer/config/locales/ locale_{LOCALE_CODE}.json file, does not get applied in the UI as per the screenshot attached herewith.

"notifications.caps":"известия",

However, changing it in the locale_bg.json file as follows worked as per the screenshot attached herewith. 

"notifications":"известия",

We need to fix this.

[1] https://docs.wso2.com/display/EI620/Customizing+Human+Task+Explorer#CustomizingHumanTaskExplorer-Addinginternationalizationandlocalization

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by vinok88** [comment]
The locale entry "notifications.caps" is used inside the Search tab, to populate the **Category** dropdown list. Please refer the screenshot below.
<img width="1440" alt="screen shot 2018-01-22 at 11 17 32 am" src="https://user-images.githubusercontent.com/1875994/35206964-2bbfe684-ff66-11e7-8e73-d284f4845f24.png">

In order to change the name of the "NOTIFICATIONS" tab name, locale entry "notifications" should be changed, which is working. The capitalization is done through the UI theme. I checked the doc also, we have not mentioned anything wrong.

Hence, there is nothing to fix.
