### ISSUE TITLE
Error when running sample.

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-ei#1562]
In the sample [1], the Stock Quote Client should log the following message (in the console):

"<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <soapenv:Fault>
            <faultcode xmlns:tns="http://www.w3.org/2003/05/soap-envelope">tns:Receiver</faultcode>
            <faultstring>Error connecting to the back end</faultstring>
        </soapenv:Fault>
    </soapenv:Body>
</soapenv:Envelope>"

However, it gives the error shown in the attached screenshot.

[1] https://docs.wso2.com/display/EI611/Sample+5%3A+Creating+SOAP+Fault+Messages+and+Changing+the+Direction+of+a+Message

![screen shot 2017-12-20 at 3 05 51 pm](https://user-images.githubusercontent.com/21237558/34200523-685512b0-e597-11e7-9591-7c2599dc0cc8.png)

**Comment by vinok88** [comment]
This is the expected behavior when used with the Stock Quote Client since our intention is to introduce fault mediators. According to the doc, above message should be returned only when a tool like SOAP UI is used. This is clearly mentioned in the doc as well. 

Please try with the SOAP UI and if the issue persists, reopen the ticket.
