### ISSUE TITLE
Removing Topics browse/add UI from EI default profile.

### ISSUE THREAD

**Issue by chanikag** [wso2/product-ei#1867]
**Description:**
The Topics UI is displayed in the EI default profile. This creates confusion when both MB profile and EI default profile are up and running and registry is shared.  Then the same topics are displayed in both MB and EI default profiles

![topics](https://user-images.githubusercontent.com/6702569/36363878-ad3ea3d8-1566-11e8-9e88-84d3be3412d3.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nuwanw** [comment]
This can not be removed since the usage of EI topic is explained in[1]. 
we can make Topic UI menu in EI different than topic  menu in broker to avoid the confusion. And also we need to fix the issue that EI topic menu listing the topics in message broker as well


[1] https://docs.wso2.com/display/IntegrationPatterns/Publish-Subscribe+Channel
