### ISSUE TITLE
[Windows][BPS] Blank page is showing when undeploying the BPMN processes

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-ei#189]
**Environment**
- OS-Windows 2012 Rc
- JAVA -jdk 1.8.0_21
- Firefox 51.0
- EI alpha pack

**Steps**
Undeploy an existing BPMN process.

**Error**
You will redirect to false blank page and undeployment will not be successful.

**Comment by himasha** [comment]
This was due to usage of <a href="javascript:deletePackages();" /> where when a value is returned from the js function (true/false) it will be appended as a string value and will try to be redirected. This is fixed with https://github.com/wso2/carbon-business-process/commit/c61f600f32bdb5ca7f861f83afd9ab05266e30c5.
