### ISSUE TITLE
Link "Known Incompatibility JDK Matrix" in the "Installation Prerequisites" of EI docs

### ISSUE THREAD

**Issue by milanperera** [wso2/product-ei#1897]
**Description:**
Currently, there is a vague explanation of the JDK incompatibility in the EI installation prerequisites page [1]. It should be enhanced and should link with the current known incompatibility JDK matrix document [2].

[1] https://docs.wso2.com/display/EI611/Installation+Prerequisites
[2] https://docs.wso2.com/display/compatibility/Known+Incompatibilities

**Affected Product Version:**
EI 6.1.1, EI 6.2.0

**Comment by praneesha** [comment]
Fixed the following in all versions of WSO2 EI. For example, see [1].

Removed the following first bullet point in the note in the "Oracle Java SE Development Kit (JDK)*" row of the table under "Required applications", because we can't say to use JDK1.8.0_144 since Mac OS does not support JDK 144.

"Use either JDK1.8.0_144 or JDK1.8.0_077 updates. We have verified that these versions are not affected by the known issue."

Also, removed the following sentence from the "Environment compatibility" section and added it as the first bullet point in the note in the "Oracle Java SE Development Kit (JDK)*" row of the table under "Required applications".

"To find out if this version of the product has issues running on your OS due to the JDK version, see Known Incompatibilities."

[1] https://docs.wso2.com/display/EI6xx/Installation+Prerequisites
