### ISSUE TITLE
Unable to manage attachments in human task explorer due to forbidden error

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1938]
**Description:**
Unable to handle the attachments in HuamnTask Explorer due to a 403 Forbidden error. 

**Affected Product Version:**
EI 6.1.1 update 23

**OS, DB, other environment details and versions:**    
OS - Ubuntu 15.10
DB - Mysql 5.6
JDK - 1.8

**Steps to reproduce:**
1. Configure claim approval process in BPS profile
2. Log in to HumanTask-Explorer
3. Select a Task  -> go to 'Attachments' -> Select a file and upload

**Observations**
Unable to manage the attachments due to 403 forbidden error.

```
[2018-03-08 14:44:27,824] [EI-Business-Process]  WARN {org.owasp.csrfguard.log.JavaLogger} -  potential cross-site request forgery (CSRF) attack thwarted (user:<anonymous>, ip:10.100.8.9, method:POST, uri:/fileupload/attachment-mgt, error:required token is missing from the request)

```
![screenshot from 2018-03-08 14-44-37](https://user-images.githubusercontent.com/14962228/37142985-bae9fa56-22df-11e8-862a-b81e27743113.png)

**Comment by arunans23** [comment]
The problem here is that, the form does not contain any CSRF-token, hence the 403 forbidden error is thrown. Adding the CSRF-token to the form would resolve this problem.

Another solution is to skip this page from owasp.properties so that CSRF token is not checked.

**Comment by arunans23** [comment]
The form element in the above page, is added on the runtime through [javascript](https://github.com/wso2/carbon-business-process/blob/master/components/humantask/humantask-explorer-web/src/web/js/actions.js#L487). Hence when the page is loaded, the CSRF-token is not added as an input to the form. To overcome the problem, we need to re-write the [page logic](https://github.com/wso2/carbon-business-process/blob/master/components/humantask/humantask-explorer-web/src/web/template/taskInstanceView.jag#L275) so that the form is loaded when the page is loaded.

**Comment by arunans23** [comment]
Even after rewriting the form logic, the issue still exists.(ie created a form in the jaggery page itself.) Due to time constraints, it was decided not to address this issue in the 6.5.0 release.
