### ISSUE TITLE
Provide the support to replace the user information maintained in the comments in ACT_HI_COMMENT

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#1993]
**Description:**
identity-anonymization-tool should be able to replace the user information in "MESSAGE_" field in ACT_HI_COMMENT table.

For example: if we provide the capability to replace the user information in the ACT_HI_COMMENT, it should support the user information maintained in the comments as well.

![screenshot from 2018-03-13 18-52-46](https://user-images.githubusercontent.com/14962228/37344207-c33b4e3a-26ef-11e8-8f65-5b718ac72d27.png)

**Comment by milanperera** [comment]
@sashikamw: I don't think we need to remove names from the comment. Because anyone can comment any other person's name there. So it does not mean that he/she put their name. For an example, let's say I'm a user of this system and I put your name there. But you are not an actual user of the system, hence we cannot identify the actual person from this comment.

For as another example, Let's say, someone put your name on the comment, but that person's intention is not to point you, but to point someone else who has the same name. For this scenario also, just by looking at the comment, we cannot identify the real user.
