### ISSUE TITLE
Documentation for EI migration from 6.1.1 to 6.2.0 should have the some important points

### ISSUE THREAD

**Issue by shavantha** [wso2/product-ei#2094]
Documentation for EI migration from 6.1.1 to 6.2.0 should have the some important points

The EI migration should discuss about moving any car files
The BPS profile document should discuss about moving any bpel and human task artifacts from 6.1.1 to 6.2.0

**Comment by pepeki** [comment]
I have opened a ticket, which might be related to your comment:  "The EI migration should discuss about moving any car files".

https://github.com/wso2/product-ei/issues/2114

**Comment by shavidissa** [comment]
Thank you!

The migration guide included the info on how to migrate the CAR files [1], BPEL and human task artifacts [2]. I added details on where to find the car files that are in 6.1.1.

[1] https://docs.wso2.com/display/EI620/Upgrading+from+WSO2+EI+6.1.1#UpgradingfromWSO2EI6.1.1-MigratingartifactsoftheIntegrationprofile
[2] https://docs.wso2.com/display/EI620/Upgrading+from+WSO2+EI+6.1.1#UpgradingfromWSO2EI6.1.1-MigratingartifactsoftheBusinessProcessprofile

**Comment by prabushi** [comment]
Artifacts which have ApplicationServer as the server role, should be changed to EnterpriseIntegrator or EnterpriseServiceBus or DataServicesServer while migrating from 6.1.1., because the 'ApplicationServer' server role is not available from EI 6.2.0 onward.
Related issue https://github.com/wso2/product-ei/issues/2114
