### ISSUE TITLE
CAR deployment broken in 6.2.0 - NoClassDefFoundError

### ISSUE THREAD

**Issue by pepeki** [wso2/product-ei#2114]
**Description:**
We have a project, where we have been using WSO2 Enterprise Integrator for a year or so. The implementation has become relatively complex over time, where it involves combination of proxies, APIs, templates, custom mediators and message broker. This gets deployed via a single CAR deployment artifact. The common code has been shared as WSO2>Extensions>JavaLibraryProject (WSO2 DevStudio).
This had been working for us just fine for all of the past releases, but got broken with WSO2 EI 6.2.0. The shared library is not loaded correctly in 6.2.0, resulting in NoClassDefFoundError.

**Suggested Labels:**
Type/Bug

**Affected Product Version:**
6.2.0
6.4.0

**Steps to reproduce:**
Enclosing a sample project, which can be used to reproduce. After CAR deployment the API gets exposed and can be tested via curl:
  `curl -X GET -H "Content-Type: application/json" http://localhost:8280/api620/test`
When deployed on WSO2 EI 6.1.1 - you get:
  `{"text": "H3110 w0r1d!"}`
When deployed on WSO2 EI 6.2.0 - an exception is raised (in the log):
  `java.lang.NoClassDefFoundError: sk/m2ms/wso2/bug/util/TestUtil`

[reproducible.zip](https://github.com/wso2/product-ei/files/1894553/reproducible.zip)

**Related Issues:**
https://github.com/wso2/product-ei/issues/2094

**Comment by prabushi** [comment]
Apparently, the payload is not set to the message context at JsonUtil class which was used at the TestMediator class mediator. We have done recent changes for JsonUtil class for https://github.com/wso2/product-ei/issues/1771

**Comment by pepeki** [comment]
That is not an issue, I wanted to highlight... 
**The deployment of the CAR does not work as expected.**
 The shared library is not loaded properly into the appropriate "classloader context". The class is not accessible from the custom mediator code.

**Comment by pepeki** [comment]
This is still issue for us, even in the latest 6.4 version of EI. This issue blocks us (our customers) from upgrading to the latest EI code.

**Comment by dakshika** [comment]
@pepeki Can you check with 6.5.0 https://wso2.com/integration/integration-studio/

**Comment by prabushi** [comment]
@pepeki 
Please find the analysis below.

In WSO2 EI 6.1.1, we have the ApplicationServer server role along with other server roles. However, 6.2.0 onward, we have removed unrelated server roles and kept only EnterpriseIntegrator,  EnterpriseServiceBus, and DataServicesServer server roles.

6.1.1
![6 1 1](https://user-images.githubusercontent.com/5234623/61540728-d1cb0580-aa5b-11e9-9638-6d3d0baf30b2.png)

6.5.0
![6 5 0](https://user-images.githubusercontent.com/5234623/61540747-dd1e3100-aa5b-11e9-9c63-437d73f27046.png)

In your osgi bundle named Library620, you have specified the server role as 'ApplicationServer'. Since, this server role is not available within the server, Library620 osgi bundle is not getting deployed in 6.2.0, and causes the java.lang.NoClassDefFoundError error from sk.m2ms.wso2.bug.TestMediator Class mediator class.

As the solution, you can change the server role of Library620 in the Composite application when you are creating the capp. Server role should be changed to EnterpriseServiceBus or EnterpriseIntegrator.
![composite-pom](https://user-images.githubusercontent.com/5234623/61542176-a4cc2200-aa5e-11e9-91da-a98e88e377f9.png)

Or, you can even manually change the server role within CAR-HOME/artifacts.xml and CAR-HOME/Library620_1.0.0/artifact.xml files.

**Comment by pepeki** [comment]
@prabushi 
I am confirming that the changing the role for the library artifact to capp/EnterpriseServiceBus in pom.xml has helped to solve our problem.
Thank you!
Peter

@dakshika 
we used the EI version 6.5.0 for verification of this fix.
