### ISSUE TITLE
WSO2 EI API URL is not overwriting based on WSDLPrefix Element

### ISSUE THREAD

**Issue by VinothChandran** [wso2/product-ei#2252]
The API endpoint url is not overwriting based on WSDLprefix element in AXIS file.
Steps:
1. Download and install WSO2 EI 6.2.0
2. update the axis2 file with below configuration in in both http & https pass through listener
parameter name="WSDLEPRPrefix" locked="false">http://test.com</parameter>
3. start the instance.
4. Proxy service URL for both http/https end point updated with below in management console
http://test.com/services/*
https://test.com/services/*
but API URL is still not updated. its still showing 
http://ip address/sampleapi

Note: the same configuration is working in WSO2 EI 6.1.1. Issue only in WSO2 EI 6.2.0

**Comment by mathieubouchard** [comment]
I looked at the code for this problem and found that the base url is created in the RestApiAdmin service (getServerContext method).

https://github.com/wso2/carbon-mediation/blob/master/components/mediation-admin/org.wso2.carbon.rest.api/src/main/java/org/wso2/carbon/rest/api/service/RestApiAdmin.java#L414

That method tries to get the hostname from the axis2 configuration and when it fails, it falls back to the local hostname, which is the IP address if there's no local DNS information that points to the IP address.

The problem is that the parameter that is used (hostname) is not defined, nor documented in the WSO2 ***axis2.xml file***. To fix this issue, we just have to add the following entry in the ***conf/axis2.xml*** file, *axisconfig* node :

```<parameter name="hostname" locked="false">test.com</parameter>```

**Comment by VinothChandran** [comment]
Thanks Mathieu. It is working after placing the hostname property.
