### ISSUE TITLE
Configuration features menu in WSO2 Enterprice Integrator on Windows not showed

### ISSUE THREAD

**Issue by marcses** [wso2/product-ei#271]
I would enable the hl7 transport on WSO2 Enterprice Integrator. The documentation says to use the feature manager under configuration->features menu; but this menu item not exist for EI 6.0.0 on Windows
![vlcoe](https://cloud.githubusercontent.com/assets/26251486/23658415/c44a3fa6-0342-11e7-9946-7d3df2567f96.png)

**Comment by vinok88** [comment]
Hi,
Thanks for reporting this.
We have removed the ability to add features from the UI due to the changes in the folder structure. You can still install the new features using Maven as explained in [1]. There are few changes required for that docs also. We will fix that soon. I have pasted the pom.xml (This also changed from default to match the new folder structure) I used to install HL7 feature below. We wll fic the documentations soon.

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"><modelVersion>4.0.0</modelVersion>
        <groupId>org.wso2.sample</groupId>
        <artifactId>sample-feature-installation</artifactId>
        <version>1.0.0</version>
        <packaging>pom</packaging>
        <name>New feature</name>
        <url>http://wso2.org</url><build><plugins><plugin><groupId>org.wso2.maven</groupId>
                                <artifactId>carbon-p2-plugin</artifactId>
                                <version>1.5.4</version>
                                <executions>
                                        <execution>
                                                <id>feature-install</id>
                                                <phase>package</phase>
                                                <goals>
                                                        <goal>p2-profile-gen</goal>
                                                </goals>
                                                <configuration>
                                                        <profile>default</profile>
                                                        <metadataRepository>http://product-dist.wso2.com/p2/carbon/releases/wilkes/</metadataRepository>
                                                        <artifactRepository>http://product-dist.wso2.com/p2/carbon/releases/wilkes/</artifactRepository>
                                                        <destination>wso2ei-6.0.0/wso2/components</destination>
                                                        <deleteOldProfileFiles>false</deleteOldProfileFiles>
                                                        <features>
                                                                <feature>
                                                                        <id>org.wso2.carbon.hl7.feature.group</id>
                                                                        <version>4.6.6</version>
                                                                </feature>
                                                        </features>
                                                </configuration>
                                        </execution>
                                </executions>
                        </plugin>
                        <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-antrun-plugin</artifactId>
                                <version>1.1</version>
                                <executions>
                                        <execution>
                                                <phase>package</phase>
                                                <configuration>
                                                        <tasks>
                                                            <replace token="false" value="true" dir="wso2ei-6.0.0/wso2/components/default/configuration/org.eclipse.equinox.simpleconfigurator">
                                                                        <include name="**/bundles.info"/>
                                                                </replace>
                                                        </tasks>
                                                </configuration>
                                                <goals>
                                                        <goal>run</goal>
                                                </goals>
                                        </execution>
                                </executions>
                        </plugin>
                </plugins>
        </build>
        <repositories><repository>
                        <id>wso2-nexus</id>
                        <name>WSO2 internal Repository</name>
                        <url>http://maven.wso2.org/nexus/content/groups/wso2-public/</url>
                        <releases>
                                <enabled>true</enabled>
                                <updatePolicy>daily</updatePolicy>
                                <checksumPolicy>ignore</checksumPolicy>
                        </releases>
                </repository>
        </repositories>
        <pluginRepositories>
        <pluginRepository>
                <id>wso2-maven-releases-repository</id>
                <url>http://maven.wso2.org/nexus/content/repositories/releases/</url>
        </pluginRepository>
        <pluginRepository>
                <id>wso2-maven-snapshots-repository</id>
                <url>http://maven.wso2.org/nexus/content/repositories/snapshots/</url>
        </pluginRepository>
</pluginRepositories>
</project>`

[1] - https://docs.wso2.com/display/Carbon440/Installing+Features+using+pom+Files

**Comment by vinok88** [comment]
Closing this issue since a solution is provided. Added a doc issue[1] to track the documentation updates.

[1] - https://github.com/wso2/product-ei/issues/275

**Comment by ikomangmahendra** [comment]
@vinok88 Could you please advise about below error? I already followed the step in [1].

Cannot complete the install because one or more required items could not be found.
 Software being installed: WSO2 Carbon - Business Adaptor HL7 Feature 4.6.6 (org.wso2.carbon.hl7.feature.group 4.6.6)
 Missing requirement: axiom 1.2.11.wso2v10 (axiom 1.2.11.wso2v10) requires 'package javax.xml 0.0.0' but it could not be found
 Missing requirement: axiom 1.2.11.wso2v11 (axiom 1.2.11.wso2v11) requires 'package javax.xml 0.0.0' but it could not be found
 Missing requirement: axiom 1.2.11.wso2v6 (axiom 1.2.11.wso2v6) requires 'package javax.xml 0.0.0' but it could not be found
 Missing requirement: axiom 1.2.11.wso2v9 (axiom 1.2.11.wso2v9) requires 'package javax.xml 0.0.0' but it could not be found
 Cannot satisfy dependency:
  From: org.wso2.carbon.business.messaging.hl7.message 4.6.6 (org.wso2.carbon.business.messaging.hl7.message 4.6.6)
  To: package org.apache.axiom.om [1.2.11,1.3.0)
 Cannot satisfy dependency:
  From: WSO2 Carbon - Business Adaptor HL7 Feature 4.6.6 (org.wso2.carbon.hl7.feature.group 4.6.6)
  To: org.wso2.carbon.business.messaging.hl7.message [4.6.6]
Application failed, log file location: C:\Users\hendra\.m2\repository\org\eclipse\tycho\tycho-p2-runtime\0.13.0\eclipse\configuration\1550124257105.log

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50.815 s
[INFO] Finished at: 2019-02-14T14:04:29+08:00
[INFO] Final Memory: 13M/98M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.wso2.maven:carbon-p2-plugin:1.5.4:p2-profile-gen (feature-install) on project sample-feature-installation: P2 publisher return code was 13 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

For your information, I have installed WSO2 version 6.4.0 on windows machine drive D:\WSO2\6.4.0
and then I put the pom.xml at that directory and execute maven command there.

**Comment by vinok88** [comment]
According to the doc [1] for EI 6.4.0, you do not have to do any feature installations for HL7 support. This issue was for an older version. You just need to enable it according to the doc. 

I'm sorry if this is not the case since I could not follow on this stuff recently.

[1] - https://docs.wso2.com/display/EI640/HL7+Transport#HL7Transport-Enablingthetransport
