### ISSUE TITLE
Retrying back-end when the call mediator is in blocking mode

### ISSUE THREAD

**Issue by malakaganga** [wso2/product-ei#3212]
**Description:**
When a single request is sent to a API and using a call mediator in blocking mode it invokes the back-end. 
But if back-end is slow it will retry the back-end in 30sec time intervals in EI-6.1.1

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI-6.1.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

Try to connect to the following API using Call mediator in Blocking mode

`<?xml version="1.0" encoding="UTF-8"?>
<api context="/api/timeout" name="apiDummyTimeout" xmlns="http://ws.apache.org/ns/synapse">
	<resource methods="POST GET">
		<inSequence>
			<script language="js">java.lang.Thread.sleep(80000);</script>
		</inSequence>
	</resource>
</api>`

**Comment by ThishaniLucas** [comment]
This issue happens when backend socket timeout is lesser than the client time out. This is the default behavior of the http client used in call-blocking scenario.

**Steps to reproduce:**

* Can use two instances of EI as client and backend.
* Deploy an API in the backend EI which responds at a considerable delay.
* Deploy a proxy or API in the client EI which calls the API in the backend EI.
* Set the passthru property 'http.socket.timeout' of the backend EI to 40 sec.
* Set the SO_TIMEOUT and the CONNECTION_TIMEOUT of the client EI to 60 sec.
* Now the client timeout is larger than the backend socket timeout.
* Call the proxy in the client EI.

We can observe three retires to the backend EI at 40 sec interval after the backend socket times out.**
