### ISSUE TITLE
[DBLookup mediator]Code snippet should be corrected

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-ei#3529]
**Description:**
Doc: https://docs.wso2.com/display/EI6xx/DBLookup+Mediator#43863dca496e4451b8499cbda00015d4

```
<statement>
        <sql>select * from company where name =?</sql>
        <parameter expression="//m0:getQuote/m0:request/m0:symbol"
                   xmlns:m0="http://services.samples/xsd" type="VARCHAR"/>
        <result name="company_id" column="id"/>
    </statement>
```
This should be corrected as below. 

```
 <statement>
                    <sql><![CDATA[select * from company where name =?]]></sql>
                    <parameter expression="//m0:getQuote/m0:request/m0:symbol" type="VARCHAR" xmlns:m0="http://services.samples/xsd"/>
                    <result column="id" name="company_id"/>
                </statement>
```

**Comment by nilminiwso2** [comment]
Fixed in EI 6.4.0 and EI 6.5.0.
The CDATA code gets added when the DBLookup mediator sample is copied to the product. Therefore, assuming that the following samples are not affected:

[1] https://docs.wso2.com/display/EI640/Sample+360%3A+Introduction+to+DBLookup+Mediator
[2] https://docs.wso2.com/display/EI640/Sample+362%3A+DBReport+and+DBLookup+Mediators+Together
[3] https://docs.wso2.com/display/EI640/Sample+363%3A+Reusable+Database+Connection+Pools

Please reopen if any further changes are required.
