### ISSUE TITLE
Docs: Update the product compatibility details

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/product-ei#3855]
The product's compatibility with other products and systems should be updated in [1].

[1] https://docs.wso2.com/display/compatibility/Compatibility+of+WSO2+Products

**Comment by samgnaniah** [comment]
Fixed.

https://docs.wso2.com/display/compatibility/Tested+Operating+Systems+and+JDKs

**Comment by a5anka** [comment]
@samgnaniah IMO the current layout of the product compatibility details is hard to read. We are listing JDK in the first column in the current layout. Can we instead list product versions in the first case? Mostly, people want to find out the supported JDKs for a product version instead of supported products for a JDK.

WDYT?
