### ISSUE TITLE
[Tooling] Cannot delete a API once created 

### ISSUE THREAD

**Issue by abeykoon** [wso2/product-ei#3865]
**Environment:**

Windows

**Description:**

1. Create a API
2. Try to delete it by right clicking on it

Getting below error

![image](https://user-images.githubusercontent.com/4967046/57129017-dfed7c00-6db2-11e9-9328-66cbaa6af85c.png)

**Comment by dakshika** [comment]
@abeykoon Is this windows only issue?

**Comment by dakshika** [comment]
not appear on MacOs. so labeled as windows

**Comment by prabushi** [comment]
This issue has occurred because this artifact has been used by some other processes in Windows environment. Hence it failed with the following error.
`The process cannot access the file because it is being used by another process.`

Similar issues have been reported for eclipse in;
[1] - https://bugs.eclipse.org/bugs/show_bug.cgi?id=463744
[2] - https://bugs.eclipse.org/bugs/show_bug.cgi?id=465364

This can happen if the relevant artifact tab is still open, if the artifact file is open, etc. If we close all the processes that use the relevant artifact, it can be deleted without a problem in Windows environment.

**Comment by abeykoon** [comment]
When I restarted Dev studio, still the issue happened. Then analysing using "Resource Monitor" on Windows, I could see that Eclipse itself has holding on to the file. 

I followed below. 

https://superuser.com/questions/117902/find-out-which-process-is-locking-a-file-or-folder-in-windows
