### ISSUE TITLE
[DOC] Missing documentation content related to call blocking mode

### ISSUE THREAD

**Issue by chanikag** [wso2/product-ei#3894]
**Description:**
When blocking mode is selected in management console UI, it shows few other options. But the description of that is missing in the documentation [1]

![image](https://user-images.githubusercontent.com/6702569/57269722-22aa9f00-70a6-11e9-9b59-3a8ecf11f6dd.png)

[1] https://docs.wso2.com/display/EI6xx/Call+Mediator

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Ibaqu** [comment]
Added description for Axis2Repository, Axis2XML and initAxis2ClientOptions for Call mediator in document [[1]](https://docs.wso2.com/display/EI6xx/Call+Mediator)

This is based on the similar descriptions from Callout Mediator since it is mentioned in the doc that Call Mediator is very similar to Callout Mediator. 

![Screen Shot 2019-05-21 at 3 31 48 PM](https://user-images.githubusercontent.com/43578935/58087348-08141200-7bde-11e9-84fd-63a4a9a4e874.png)

Please advise

[1] - https://docs.wso2.com/display/EI6xx/Call+Mediator
