### ISSUE TITLE
[Docs][JMS] Update docs with JMS 2.0 related configurations  

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-ei#398]
Please update following docs related to JMS 2.0

1. JMS Inbound Protocol [1]
Update transport.jms.JMSSpecVersion with possible value as 2.0

2. JMS 2.0 use cases should update with mandatory parameters

Shared Topic Subscription with WSO2 EI [2] - When enabling shared subscription, we need to add 
- transport.jms.JMSSpecVersion as 2.0
- transport.jms.SharedSubscription as true
- Should add same name for transport.jms.DurableSubscriberName

[1] https://docs.wso2.com/display/Ei600/JMS+Inbound+Protocol
[2] 
https://docs.wso2.com/display/EI600/Shared+Topic+Subscription+with+WSO2+EI

**Comment by praneesha** [comment]
1. Fixed by Nisrin.

2. Added the following note in [1] in both EI 6.0.0 & 6.1.0 docs.

"Make sure to configure the below properties as follows when setting up the inbound endpoint:
Set the value of the transport.jms.JMSSpecVersion property as 2.0.
Set the value of the transport.jms.SharedSubscription propoerty as true.
Specify a subscriber name as the value of the transport.jms.DurableSubscriberName property and use the same for all subscribers."

[1] https://docs.wso2.com/display/EI610/Shared+Topic+Subscription+with+WSO2+EI
