### ISSUE TITLE
[Docs]Update docs to reflect deleted wso2ei-samples.sh file

### ISSUE THREAD

**Issue by samgnaniah** [wso2/product-ei#4011]
The wso2ei-samples.sh file (#3935) is deleted. Samples documentation needs to be updated.

**Comment by samgnaniah** [comment]
Fixed.

**Comment by arunans23** [comment]
A lot of documents pages still reflect the usage of samples script. 
For eg : https://docs.wso2.com/display/EI650/Sample+500%3A+Call+Mediator+for+Non-Blocking+Service+Invocation (You can search for "sn" in the document space, and you can access most of the mistaken pages.)

We need to find all the instances and fix this.

**Comment by arunans23** [comment]
We can edit the documentation like this. 
Instead of saying to start the esb with the sample configuration, we can say "Create the above configuration in the WSO2 ESB profile."

Please note : we have to make changes in both 6.5.0 and 6xx document space.

**Comment by praveennadarajah** [comment]
Most of the changes have been added to 6xx document space.

**Comment by KasunAratthanage** [comment]
@samgnaniah This issue can be closed.

**Comment by AyeshUvindu** [comment]
In the EI 6.6.0 documentation[2], this [1] Image is showing about the wso2ei-samples.sh. Customers are getting confused because of this. Can you please correct this image. It will be great if we can properly explain this in the documentation. 

[1].https://docs.wso2.com/download/attachments/141242399/ESB-Samples.png?version=1&modificationDate=1576210677000&api=v2
[2].https://docs.wso2.com/display/EI660/Setting+Up+the+ESB+Samples#SettingUptheESBSamples-ESBSamplePrerequisites

**Comment by AyeshUvindu** [comment]
Hi team, can you please let us know an ETA for correcting this issue

**Comment by samgnaniah** [comment]
I have updated the image in [1] removing the mention of wso2ei-samples.sh. Please check and let me know if more changes are required.

[1] https://docs.wso2.com/display/EI660/Setting+Up+the+ESB+Samples
