### ISSUE TITLE
[EI 6.1][Tooling] Properties tab becomes blank when you click on other tabs

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#402]
1. Create a Rest API from design view. 
2. Include a Send mediator
3. Include an HTTP Endpoint in design view.
4. Double click on endpoint to set properties.
5. Now click on Markers/ Servers /Snippets or any tab on the top menu.
6. Now click back on Properties tab.
7. It will be blank.

![screenshot from 2017-03-28 15-51-08](https://cloud.githubusercontent.com/assets/12966170/24400543/5f9df45c-13ce-11e7-8056-5e64dc373724.png)

**Comment by vinok88** [comment]
This is the normal behavior. I checked in ESB tooling also.Properties tab is blank since nothing is selected. If you click on the endpoint again, properties are visible.

**Comment by ushanib** [comment]
That is true, but a user should be able to set the properties and making it blank is not acceptable.

**Comment by prabushi** [comment]
Property pane is only focused on the selected artifact. Once we click and select a particular artifact, properties pane will be populated with related attributes which are to be updated. Once we click on another tab, since there is no selected artifact at that time, the properties pane will become blank.
