### ISSUE TITLE
Update 6.5.0 doc on starting ESB Profile

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#4120]
**Description:**
$subject.

In most of the docs, it still points to 6.4.0.

https://docs.wso2.com/display/EI650/Exposing+Data+as+an+OData+Service#ExposingDataasanODataService-ExposetheRDBMSasanODataservice

https://docs.wso2.com/display/EI650/Handling+Distributed+Transactions#HandlingDistributedTransactions-Addingthedatasourcestoadataservice

Start the WSO2 ESB profile section need to be updated.

In all places here, we are assuming that the user has used the installers. Isn't it better if we provide the instructions to start if they have used binary also. cc: @abeykoon 

IMO , this section can be referred from a common place, otherwise, we would need to update this for all releases.

**Comment by nilminiwso2** [comment]
6.4.0 references are now changed to 6.5.0.

**Comment by nilminiwso2** [comment]
Updated product installation instructions:

- The Integration Tutorials (because they use Integration Studio to start the server) will use the binary [1].
- Other tutorials (DSS, MB, and BPS) + QSG use the installer as they don't start the servers from Integration Studio.
-The installation guide gives the balanced message about the installation options [2].

[1] https://docs.wso2.com/display/EI650/Integration+Tutorials
[2] https://docs.wso2.com/display/EI650/Installation+Guide
