### ISSUE TITLE
Deployment issues faced when working with BPMN packages

### ISSUE THREAD

**Issue by nandika** [wso2/product-ei#4568]
**Description:**
Following two issues happen when working with BPMN packages. EI version 6.4.0

1.  package deployment with the same name will undeploy all existing previous deployments
2. Issue in a code/runtime variable will not let the undeployment of all current and future deployments of the same package

**Suggested Labels:**
BPMN, Deployment

**Suggested Assignees:**

**Affected Product Version:**
EI 6.4.0 

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sameeragunarathne** [comment]
> 1. package deployment with the same name will undeploy all existing previous deployments

This case was reproduced and was able to resolve this using the resolveDeploymentsAtStartup  parameter when starting the server. 
sh bin/wso2server.sh -DresolveDeploymentsAtStartup=false 


> 2. Issue in a code/runtime variable will not let the undeployment of all current and future deployments of the same package

This behavior was not reproduced for the both the scenarios(with/without) parameter.

**Comment by sameeragunarathne** [comment]
This was reproduced when there are active instances more than 1000 for a process. This was due to a fix that was introduced for management console UI unresponsiveness issue[1]. To overcome this user has to manually delete the active instances using process clean up tool.

[1] - https://wso2.org/jira/browse/BPS-797
