### ISSUE TITLE
Upgrade Hazelcast dependency to 4.0

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/product-ei#4810]
**Description:**
The Hazelcast dependency needs to be upgraded to 4.0 once it is released since a number of improvements are done in this release.

**Comment by sdkottegoda** [comment]
We are specifically looking forward for the fixes of https://github.com/hazelcast/hazelcast/issues/14083 and https://github.com/hazelcast/hazelcast/issues/13699

**Comment by malakaganga** [comment]
Hi ,
As given in [1], In version 4.0, ILock and ICondition interfaces are completely removed. But in our code (ex: ode, carbon-mediation, https://github.com/wso2/carbon-mediation/blob/master/components/mediation-clustering/src/main/java/org/wso2/carbon/mediation/clustering/ClusteringServiceUtil.java#L64)

These implementations have been used so due to this API changes we are not going to do this update for this immediate release  hence we will add this as a future task

[1] https://docs.hazelcast.org/docs/latest-dev/manual/html-single/#removal-of-deprecated-concurrency-api-implementations
