### ISSUE TITLE
Message body getting dropped when 202 received in call blocking mode.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-ei#4811]
**Description:**

When the back end respond with HTTP status code 202 and payload, payload is being dropped in EI.

**Affected Product Version:**

 EI 6.4.0  ( wum updated pack - 27th Nov 2019 ).

**Steps to reproduce:**

1. Deploy the below proxy in EI 640 wum updated pack.

```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse"
       name="accepted"
       transports="http https"
       startOnLoad="true">
   <description/>
   <target>
      <inSequence>
         <call blocking="true">
            <endpoint>
               <address uri="http://www.mocky.io/v2/5ddcbf1c3400005800eae3d8"/>
            </endpoint>
         </call>
         <log level="full"/>
         <property name="NO_ENTITY_BODY" scope="axis2" action="remove"/>
         <respond/>
      </inSequence>
   </target>
</proxy>
```

2. Invoke the proxy.
3. In response, we can see that the payload is replaced with empty body.

P.S This works in 6.4.0 vanilla pack.

**Related Issues:**
https://github.com/wso2/product-ei/issues/4695

**Comment by PetteriPertola** [comment]
**This happens also if status code is 200 and in version 6.6.0** 
Is there a work around?
Please add this to the documentation as it's super frustrating to spend hours not understanding why something doesn't work when there is a known issue like this one affecting what is a standard call!

**Comment by Vathsan** [comment]
Hi @PetteriPertola,

We used the following synapse configuration and tested in EI 6.6.0 vanilla pack but could not observe such a behaviour.
```
<?xml version="1.0" encoding="UTF-8"?><proxy xmlns="http://ws.apache.org/ns/synapse" name="accepted" startOnLoad="true" statistics="disable" trace="disable" transports="http,https">
    <target>
        <inSequence>
            <call blocking="true">
                <endpoint>
                    <address uri="http://run.mocky.io/v3/8ae60822-c281-4b64-b80a-010bb5ed21ee"/>
                </endpoint>
            </call>
            <log level="full"/>
            <property action="remove" name="NO_ENTITY_BODY" scope="axis2"/>
            <property name="messageType" scope="axis2" value="application/json"/>
            <respond/>
        </inSequence>
    </target>
    <description/>
</proxy>
```
Could you please share the synapse configuration?

**Comment by PetteriPertola** [comment]
Hi,
You are right. I was compiling my configuration as it is converting from JMS queue into the REST API from proxy service -> sequence -> sequence -> REST API, and while doing that I noticed I had the property OUT_ONLY set to true in the proxy service, as that was previously using an asynchronous flow instead of a synchronous REST flow as it is doing now. 

This is the reason why the response is being ignored - once I removed it, it worked. 

I wish this would be flagged somehow by IntegrationStudio as such small things are very easy to miss and you can spend days debugging as a result.

You can ignore the above as it is resolved now.
