### ISSUE TITLE
[Doc?] Json Transform Mediator in EI 7?

### ISSUE THREAD

**Issue by stefanonegri** [wso2/product-ei#4969]
**Description:**
Hi, is the Json Transform Mediator available in EI 7? if not mistaking, I cannot find in the documentation and I can't find in the Integration Studio either. In EI 6.6, it is available in the doc but how about Integration Studio? is Integration Studio for 6.6 different that the 7 version?
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI 7, EI 6.6
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by arunans23** [comment]
@stefanonegri  JSON Transform mediator was released with EI 6.6.0 which was released after EI 7. Hence, the mediator is not available in EI 7 Micro Integrator. 

In the case of Integration Studio 7.0, it originally did not have support for JSON Transform mediator. But later it was provided via an update since Integration Studio 7.0 has to be compatible with EI 6.6. You can update the Integration Studio and use it with EI 6.6. 

Please note that the Micro Integrator runtime which is packed inside the Integration Studio does not have the JSON Transform mediator feature. You need to point a EI 6.6 server, if you want to test the feature from Integration Studio.
