### ISSUE TITLE
[Doc][EI610][JMS Transactions]Sample client configs should be added

### ISSUE THREAD

**Issue by Dilshani** [wso2/product-ei#504]
While referring jms transactions doc[1], it point out a client as follows;

`ant jmsclient -Djms_type=pox -Djms_dest=dynamicQueues/StockQuoteProxy -Djms_payload=MSFT`

This client not going to work with broker profile as this hard coded with activemq configurations. Docs should updated with that details.

[1] https://docs.wso2.com/display/EI600/JMS+Transactions

**Comment by praneesha** [comment]
Added the following note in docs of WSO2 EI 6.1.0 and below.

"Currently, it is a [known issue](https://github.com/wso2/product-ei/issues/766) that this client does not work with the Broker profile of WSO2 EI. This will be fixed in future releases."

Created an issue to fix this in the product in WSO2 EI 6.2.0 in [1].

[1] https://github.com/wso2/product-ei/issues/766
