### ISSUE TITLE
[6.4.0] Cannot create sequences with "xml-multiple" through the console UI

### ISSUE THREAD

**Issue by rahalJayawardane** [wso2/product-ei#5107]
**Description:**
We cannot create or edit simple sequences in the management console when we have the ```<?xml-multiple ?>``` tag. 
However, we can deploy similar sequences through a CAR file and can edit/save through the file system ( <EI_HOME>/repository/deployment/server/synapse-configs/default/sequences).

Product: EI-6.4.0 (latest WUM updated pack)

**Suggested Labels:**
EI, 6.4.0, xml-multiple, UI

**Steps to reproduce:**
1. Login to carbon console
2. Try to create a new sequence and save it.

Sample Sequence: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sequence name="sampleSeq" xmlns="http://ws.apache.org/ns/synapse">
    <payloadFactory media-type="xml">
        <format>
            <jsonObject>
                <data><?xml-multiple ?>
                    $1
                </data>
            </jsonObject>
        </format>
        <args>
            <arg evaluator="xml" value="sample"
                literal="false" xmlns:ns="http://org.apache.synapse/xsd"/>
        </args>
    </payloadFactory>
    <property name="messageType" scope="axis2" type="STRING" value="application/json"/>
    <respond/>
</sequence>
```

**Comment by sdkottegoda** [comment]
Our recommendation is to not edit sequences using the management console because they will be reset after a CApp redeployment or a server restart. We need to edit the CApp properly and and perform a redeployment. This is the main reason why we have removed this capability with the latest MI versions.

Hence, we will not be fixing this unless we get a considerable number of requests.
