### ISSUE TITLE
Format to JSON after the payload is built in syanpse level preserving the primitive type in the original payload

### ISSUE THREAD

**Issue by chanikag** [wso2/product-ei#578]
In mediator level, (synapse level) we do the processing in XML even though the original payload is in JSON. When it converts to JSON, it converts the values according to the primitive value. For an example 1 in the xml payload converts to 1 even though it is "1" in the original JSON payload. This can be eliminated by setting,
synapse.commons.json.output.autoPrimitive=false 

But it converts all the values to string. 
Or else can go with the solution in [1], but it requires to know the payload format in advance at the deployment time, which is not the case always. Also it adds XSLT  transformation overhead at each request. Therefore, it requires to have a way to output JSON payload without any primitive type conversion.

[1] https://wso2.org/jira/browse/ESBJAVA-4781

**Comment by riyafa** [comment]
In synapse staxon is used for XML to JSON and JSON to XML conversion. Hence the staxon mapping convention is used[1]. In this convention the values in a JSON input is considered the same in all conversions. I meant whether it is a primitive type such as numbers, true, false or null still it is converted in the same way as when the value is a double quoted string. Hence when this is converted back from XML to JSON there is no way to identify whether it is a primitive type or a double quoted string. 
To fix this we need to change the convention of mapping JSON to XML. That is we need to change the convention on how primitive types should be represented in XML to differentiate it from the double quoted values. 
We cannot do this on our own since we have been using the staxon mapping convention so far. Hence I created an issue[2] in staxon asking for suggestions.

[1]https://github.com/beckchr/staxon/wiki/Mapping-Convention
[2] https://github.com/beckchr/staxon/issues/45
