### ISSUE TITLE
[6.2.0][Windows 10] Passwords are not encrypted when you run securevault

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#750]
Environment 
=========
JDK 1.8,
Windows 10,
Pre m1 pack with analytics improvements

Run the below command in Windowd 10.
bin\ciphertool.bat -Dconfigure

It will ask for the keystore password and give the successful message as it the configuration saved.

But when you check the user-mgt.xml and master-datasources.xml passwords are in text mode. Not encrypted.

**Comment by ushanib** [comment]
Issue exists in m1 pack as well

**Comment by Manuri** [comment]
Hi, 
This functionality is working in windows.
The issue here is in ciphertool.bat when setting CARBON_HOME we have used the "set" command which seems to be persisting the variable to the environment even after the execution of the batch file. So if we try to use ciphertool in the same command prompt for a different server since the CARBON_HOME is different it won't work. 
I suppose this could be solved by using "set local" instead of "set" in bat file.
