### ISSUE TITLE
[Doc] Provide a guide to admin service

### ISSUE THREAD

**Issue by sashikamw** [wso2/product-ei#787]
In the current EI 620 documentation, there is no reference to admin services, would be better to add a page describing how to access the admin services or referring to an existing carbon level documentation.

In ESB 490 doc - https://docs.wso2.com/display/ESB490/Calling+Admin+Services+from+Apps doc exists but could not find this in EI Docs

**Comment by praneesha** [comment]
Added the page in all WSO2 EI versions. For example, see [1].

We can't move this to the Common Admin Guide, since this is not an administrative task. Admin services are used to access internal information of the product similar to the functionality of APIs.

[1] https://docs.wso2.com/display/EI600/Calling+Admin+Services+from+Apps
