### ISSUE TITLE
[Doc] Include a list of artifacts that should be paid attention when upgrading in to a new version

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#788]
[Doc] Include a list of artifacts that should be paid attention when upgrading in to a new version and how those can be upgraded.

E.g.,
From ESB 5.0.0 and onward, We have stopped processing mediators after the send mediator in the given sequence because of It may lead to erroneous behavior when the message stream is consumed by send mediator when passthru scenarios. 
So It is not a best practice to add mediators after send mediator and even the developer studio also not allowed to add mediators after send. 
Best way is to process message after send is having a clone mediator. Then It will clone the message and process the message separately.

This can mentioned in document [1]. This is just a sample. We need to find a list and provide a solution in our upgrading documentation. May be we can link to relatd mediators/solutions in other pages.
[1] https://docs.wso2.com/display/ESB500/Upgrading+from+a+Previous+Release#99fa569146974d10a1d0e6096e09a167

**Comment by praneesha** [comment]
Added a note in docs of WSO2 ESB 5.0.0[1] and all versions of WSO2 EI[2]. 

"From WSO2 ESB 5.0.0 onwards, it does not support processing any mediators added after the send mediator in a given sequence because it may lead to erroneous behaviors when the message stream is consumed by the send mediator in passthrough scenarios. Therefore, if you have sequences with mediators after the send mediator, you need to change those sequences to have the send mediator inside a clone mediator, thereby, it will clone the message and process it separately. For example, see below."     

Changes affecting migrations will be tracked via Pull Requests in future. Email [3] discussed how it will be done for existing product versions.

[1] https://docs.wso2.com/display/ESB500/Upgrading+from+a+Previous+Release
[2] https://docs.wso2.com/display/EI620/Upgrading+from+WSO2+Enterprise+Service+Bus
[3] [EI DOCS] - Capturing Changes in Artifacts or Upgrading
