### ISSUE TITLE
Enrich mediator clone property default value should be corrected as "true"

### ISSUE THREAD

**Issue by prabushi** [wso2/product-ei#875]
[1] - https://docs.wso2.com/display/EI611/Enrich+Mediator#SourceConfiguration

**Comment by praneesha** [comment]
As discussed with Prabushi, the issue is that although we have set the default value of the clone property to true in the code, the UI implementation has been done showing it as false.

However, the UI is corrected in WSO2 EI 6.2.0. Therefore, changed the screenshot in [1].

In earlier versions, corrected the following sentence.

" The default value is true"

We do not need to fix and example because the clone property is set in them. Issue occurs when you don't set it so that the default value gets applied.

[1] https://docs.wso2.com/display/EI620/Enrich+Mediator
