### ISSUE TITLE
Messages are not automatically moved to dead letter channel (DLC) - broker - wso2 ei

### ISSUE THREAD

**Issue by fshomou** [wso2/product-ei#923]
Hi, 

 Im using WSO2 EI 6.1.1, and trying to create message queue with message store and message processor with an endpoint. 

When I shutdown my endpoint, the message processor is deactivated and the messages stay in the queue and they are not moved to DLC. 

What should  I do to make it work ?

[endpoint.txt](https://github.com/wso2/product-ei/files/1246336/endpoint.txt)
[MessageProQueueCase.txt](https://github.com/wso2/product-ei/files/1246337/MessageProQueueCase.txt)
[MessageStoreQueueCase.txt](https://github.com/wso2/product-ei/files/1246335/MessageStoreQueueCase.txt)
[proxy.txt](https://github.com/wso2/product-ei/files/1246338/proxy.txt)

Thanks, 

Faris Shomou

**Comment by pamod** [comment]
Faris,

This is expected behavior, the broker will send the messages to DLC after the number of retry counts have breached. 

Based on your query the messages could still be in the queue since the messages has not got retried for the number of times specified in the broker.xml.

You could refer the details from https://docs.wso2.com/display/EI611/Using+the+Dead+Letter+Channel#UsingtheDeadLetterChannel-Configuringthemessageretrycount 

The above will guide you through the process of modifying the retry counts.

**Comment by fshomou** [comment]
Thanks Pamod. But why the message processor parameter (max.delivery.attempts) is not working ?
I have configured this parameter to 5 par example, and the message processor was deactivate for the first attempt. 
The message processor should not be deactivates before reaching the max.delivery.attempts, yes or non ?
