### ISSUE TITLE
Expired messages are not marked as 'expired' on the console

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/product-ei#925]
The MB console does not mark expired messages as 'expired' (or with a similar wording). Due to this reason, it is unable to recognize expired messages that won't be delivered when consumers subscribe.

**Comment by a5anka** [comment]
Normally if broker detects an expired message, that message will be **deleted** from the message store rather than flagging them. Therefore ideally the expired message shouldn't be there at all. But since the `periodicMessageDeletionInterval` by default is 15 minutes, there can be some messages which are not detected as expired until the periodic message deletion task is run. 

[1] https://docs.wso2.com/display/MB320/Configuring+Message+Expiration
